# Generated by Django 2.2 on 2019-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_auto_20190416_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='player_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='game_status',
            field=models.BooleanField(default=True),
        ),
    ]
