# Generated by Django 2.2 on 2019-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_auto_20190417_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='play_as',
            field=models.CharField(default='Player', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
