# Generated by Django 2.2 on 2019-04-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0006_auto_20190418_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
    ]
