# Generated by Django 2.2 on 2019-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_auto_20190423_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
