# Generated by Django 2.2 on 2019-05-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0009_auto_20190423_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='game_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
