# Generated by Django 2.2 on 2019-05-02 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0010_auto_20190501_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gameapp.Game'),
        ),
    ]
